openapi: 3.0.1
info:
  description: APIs for managing CC administrators.
  title: Administrators APIs
  version: 1.0.0
servers:
- description: For customers in Commercial citrix cloud
  url: https://api.cloud.com/administrators
- description: For customers in JP region
  url: https://api.citrixcloud.jp/administrators
paths:
  /:
    get:
      operationId: FetchAdministrators
      parameters:
      - description: Optional administrator type filter.
        explode: true
        in: query
        name: type
        required: false
        schema:
          maxLength: 256
          minLength: 0
          type: string
        style: form
      - description: Optional provider type.
        explode: true
        in: query
        name: providerType
        required: false
        schema:
          $ref: '#/components/schemas/AdministratorProviderType'
        style: form
      - description: Optional item count.
        explode: true
        in: query
        name: maxItemCount
        required: false
        schema:
          maxLength: 256
          minLength: 0
          pattern: "^[0-9]+$"
          type: string
        style: form
      - description: Optional continuation token.
        explode: true
        in: query
        name: requestContinuation
        required: false
        schema:
          maxLength: 8192
          minLength: 0
          type: string
        style: form
      - description: "User ID corresponding to a user administrator. (Note: Exclusive\
          \ with other parameters on this endpoint.)"
        explode: true
        in: query
        name: id
        required: false
        schema:
          maxLength: 100
          minLength: 0
          type: string
        style: form
      - description: Access token.
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - description: Customer ID.
        explode: false
        in: header
        name: Citrix-CustomerId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdministratorsResult'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      summary: Fetch all CC administrators.
      tags:
      - Administrators
  /{id}/access:
    get:
      operationId: GetAdministratorAccess
      parameters:
      - description: UserId for AzureAd and Citrix User Administrators. UcOid for
          all others.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdministratorAccessModel'
          description: Success
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      summary: Fetch the access of an administrator.
      tags:
      - Administrators
  /$create:
    post:
      operationId: CreateAdministrator
      parameters:
      - description: Access token.
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - description: Customer ID.
        explode: false
        in: header
        name: Citrix-CustomerId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAdministratorInputModel'
        description: Administrator to be added.
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdministratorResult'
          description: Success
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      summary: Create a new CC administrator.
      tags:
      - Administrators
  /access:
    put:
      operationId: UpdateAdministratorAccess
      parameters:
      - description: CC administrator ID.
        explode: true
        in: query
        name: id
        required: true
        schema:
          maxLength: 100
          minLength: 0
          type: string
        style: form
      - description: Access token.
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - description: Customer ID.
        explode: false
        in: header
        name: Citrix-CustomerId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdministratorAccessModel'
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      summary: Update roles and permissions of an existing CC administrator.
      tags:
      - Administrators
  /{id}:
    delete:
      operationId: DeleteAdministrator
      parameters:
      - description: CC administrator ID.
        explode: false
        in: path
        name: id
        required: true
        schema:
          maxLength: 100
          minLength: 0
          type: string
        style: simple
      - description: Access token.
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - description: Customer ID.
        explode: false
        in: header
        name: Citrix-CustomerId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      summary: Remove a CC administrator.
      tags:
      - Administrators
  /invitations:
    delete:
      operationId: DeleteInvitation
      parameters:
      - description: Pending user administrator invitation email.
        explode: true
        in: query
        name: email
        required: true
        schema:
          format: email
          maxLength: 256
          minLength: 0
          type: string
        style: form
      - description: Access token.
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - description: Customer ID.
        explode: false
        in: header
        name: Citrix-CustomerId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Success
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      summary: Remove a CC pending user administrator invitation.
      tags:
      - Administrators
components:
  schemas:
    AdministratorAccessModel:
      example:
        accessType: Full
        policies:
        - checkable:
            canChangeValue: true
            value: true
          displayName: displayName
          name: notifications
          scopeChoices:
            allScopesSelected: true
            choices:
            - checkable:
                canChangeValue: true
                value: true
              displayName: displayName
              name: name
            - checkable:
                canChangeValue: true
                value: true
              displayName: displayName
              name: name
          serviceName: Platform
        - checkable:
            canChangeValue: true
            value: true
          displayName: displayName
          name: notifications
          scopeChoices:
            allScopesSelected: true
            choices:
            - checkable:
                canChangeValue: true
                value: true
              displayName: displayName
              name: name
            - checkable:
                canChangeValue: true
                value: true
              displayName: displayName
              name: name
          serviceName: Platform
      properties:
        accessType:
          $ref: '#/components/schemas/AdministratorAccessType'
        policies:
          items:
            $ref: '#/components/schemas/AdministratorAccessPolicyModel'
          nullable: true
          type: array
      required:
      - accessType
      type: object
    AdministratorAccessPolicyModel:
      example:
        checkable:
          canChangeValue: true
          value: true
        displayName: displayName
        name: notifications
        scopeChoices:
          allScopesSelected: true
          choices:
          - checkable:
              canChangeValue: true
              value: true
            displayName: displayName
            name: name
          - checkable:
              canChangeValue: true
              value: true
            displayName: displayName
            name: name
        serviceName: Platform
      properties:
        name:
          example: notifications
          minLength: 1
          pattern: "^[a-zA-Z0-9_\\-]{1,36}$"
          type: string
        serviceName:
          example: Platform
          minLength: 1
          pattern: "^[a-zA-Z0-9_\\-]{1,36}$"
          type: string
        displayName:
          maxLength: 256
          minLength: 0
          nullable: true
          type: string
        checkable:
          $ref: '#/components/schemas/BooleanPolicyProperty'
        scopeChoices:
          $ref: '#/components/schemas/AdministratorAccessScopeChoices'
      required:
      - checkable
      - name
      - serviceName
      type: object
    AdministratorAccessScopeChoices:
      example:
        allScopesSelected: true
        choices:
        - checkable:
            canChangeValue: true
            value: true
          displayName: displayName
          name: name
        - checkable:
            canChangeValue: true
            value: true
          displayName: displayName
          name: name
      properties:
        allScopesSelected:
          type: boolean
        choices:
          items:
            $ref: '#/components/schemas/AdministratorAccessScopeChoicesModel'
          nullable: true
          type: array
          example: null
      type: object
    AdministratorAccessScopeChoicesModel:
      example:
        checkable:
          canChangeValue: true
          value: true
        displayName: displayName
        name: name
      properties:
        name:
          minLength: 1
          pattern: "^[a-zA-Z0-9_\\-]{1,36}$"
          type: string
        displayName:
          maxLength: 256
          minLength: 0
          nullable: true
          type: string
        checkable:
          $ref: '#/components/schemas/BooleanPolicyProperty'
      required:
      - checkable
      - name
      type: object
    AdministratorType:
      enum:
      - AdministratorUser
      - AdministratorGroup
      - ServicePrincipal
      type: string
    AdministratorAccessType:
      enum:
      - Full
      - Custom
      - Reinvite
      type: string
    AdministratorExternalProviderType:
      enum:
      - AzureAd
      - Ad
      - Okta
      - Google
      type: string
    AdministratorNotification:
      example:
        type: Error
        enabled: true
      properties:
        type:
          $ref: '#/components/schemas/AdministratorNotificationType'
        enabled:
          nullable: true
          type: boolean
      type: object
    AdministratorNotificationType:
      enum:
      - Error
      - Warning
      - Information
      - Critical
      type: string
    AdministratorNotificationsEmailsPreferences:
      example:
        enabledDate: 2000-01-23
        sendNotificationEmails: true
        notificationsSubscribed:
        - type: Error
          enabled: true
        - type: Error
          enabled: true
      properties:
        sendNotificationEmails:
          type: boolean
        notificationsSubscribed:
          items:
            $ref: '#/components/schemas/AdministratorNotification'
          nullable: true
          type: array
        enabledDate:
          format: date
          nullable: true
          type: string
      required:
      - sendNotificationEmails
      type: object
    AdministratorProviderType:
      enum:
      - Ad
      - AzureAd
      - CitrixSts
      - Google
      type: string
    AdministratorResult:
      additionalProperties: {}
      example:
        lastName: lastName
        ucOid: ucOid
        displayName: displayName
        pending: true
        providerProperties:
          displayName: displayName
          tid: tid
        emailPreferences: emailPreferences
        updatedDate: 2000-01-23T04:56:07.000+00:00
        type: AdministratorUser
        userId: userId
        providerType: Ad
        authDomain: authDomain
        accessType: Full
        firstName: firstName
        invitationExpired: true
        createdDate: 2000-01-23T04:56:07.000+00:00
        providerId: providerId
        legacyProviders:
        - legacyProviders
        - legacyProviders
        customerId: customerId
        serviceProfile: serviceProfile
        externalOid: externalOid
        eTag: eTag
        email: email
        notificationsEmailPreferences:
          enabledDate: 2000-01-23
          sendNotificationEmails: true
          notificationsSubscribed:
          - type: Error
            enabled: true
          - type: Error
            enabled: true
      properties:
        customerId:
          nullable: true
          type: string
        ucOid:
          nullable: true
          type: string
        userId:
          nullable: true
          type: string
        type:
          $ref: '#/components/schemas/AdministratorType'
        accessType:
          $ref: '#/components/schemas/AdministratorAccessType'
        serviceProfile:
          maxLength: 100
          minLength: 0
          nullable: true
          type: string
        firstName:
          maxLength: 100
          minLength: 0
          nullable: true
          type: string
        lastName:
          maxLength: 100
          minLength: 0
          nullable: true
          type: string
        displayName:
          maxLength: 256
          minLength: 0
          nullable: true
          type: string
        email:
          nullable: true
          type: string
        providerType:
          $ref: '#/components/schemas/AdministratorProviderType'
        providerId:
          nullable: true
          type: string
        providerProperties:
          $ref: '#/components/schemas/AdministratorResult_providerProperties'
        externalOid:
          nullable: true
          type: string
        emailPreferences:
          nullable: true
          type: string
        notificationsEmailPreferences:
          $ref: '#/components/schemas/AdministratorNotificationsEmailsPreferences'
        authDomain:
          nullable: true
          type: string
        pending:
          nullable: true
          type: boolean
        invitationExpired:
          nullable: true
          type: boolean
        legacyProviders:
          items:
            type: string
          nullable: true
          type: array
        createdDate:
          format: date-time
          nullable: true
          type: string
        updatedDate:
          format: date-time
          nullable: true
          type: string
        eTag:
          nullable: true
          type: string
      type: object
    AdministratorsResult:
      example:
        items:
        - lastName: lastName
          ucOid: ucOid
          displayName: displayName
          pending: true
          providerProperties:
            displayName: displayName
            tid: tid
          emailPreferences: emailPreferences
          updatedDate: 2000-01-23T04:56:07.000+00:00
          type: AdministratorUser
          userId: userId
          providerType: Ad
          authDomain: authDomain
          accessType: Full
          firstName: firstName
          invitationExpired: true
          createdDate: 2000-01-23T04:56:07.000+00:00
          providerId: providerId
          legacyProviders:
          - legacyProviders
          - legacyProviders
          customerId: customerId
          serviceProfile: serviceProfile
          externalOid: externalOid
          eTag: eTag
          email: email
          notificationsEmailPreferences:
            enabledDate: 2000-01-23
            sendNotificationEmails: true
            notificationsSubscribed:
            - type: Error
              enabled: true
            - type: Error
              enabled: true
        - lastName: lastName
          ucOid: ucOid
          displayName: displayName
          pending: true
          providerProperties:
            displayName: displayName
            tid: tid
          emailPreferences: emailPreferences
          updatedDate: 2000-01-23T04:56:07.000+00:00
          type: AdministratorUser
          userId: userId
          providerType: Ad
          authDomain: authDomain
          accessType: Full
          firstName: firstName
          invitationExpired: true
          createdDate: 2000-01-23T04:56:07.000+00:00
          providerId: providerId
          legacyProviders:
          - legacyProviders
          - legacyProviders
          customerId: customerId
          serviceProfile: serviceProfile
          externalOid: externalOid
          eTag: eTag
          email: email
          notificationsEmailPreferences:
            enabledDate: 2000-01-23
            sendNotificationEmails: true
            notificationsSubscribed:
            - type: Error
              enabled: true
            - type: Error
              enabled: true
        continuationToken: continuationToken
      properties:
        continuationToken:
          maxLength: 8192
          minLength: 0
          nullable: true
          type: string
        items:
          items:
            $ref: '#/components/schemas/AdministratorResult'
          nullable: true
          type: array
      type: object
    BooleanPolicyProperty:
      example:
        canChangeValue: true
        value: true
      properties:
        value:
          type: boolean
        canChangeValue:
          type: boolean
      type: object
    CreateAdministratorInputModel:
      example:
        accessType: Full
        firstName: Jenny
        lastName: Rosen
        externalUserId: externalUserId
        displayName: Jenny Rosen
        externalProviderId: externalProviderId
        policies:
        - checkable:
            canChangeValue: true
            value: true
          displayName: displayName
          name: notifications
          scopeChoices:
            allScopesSelected: true
            choices:
            - checkable:
                canChangeValue: true
                value: true
              displayName: displayName
              name: name
            - checkable:
                canChangeValue: true
                value: true
              displayName: displayName
              name: name
          serviceName: Platform
        - checkable:
            canChangeValue: true
            value: true
          displayName: displayName
          name: notifications
          scopeChoices:
            allScopesSelected: true
            choices:
            - checkable:
                canChangeValue: true
                value: true
              displayName: displayName
              name: name
            - checkable:
                canChangeValue: true
                value: true
              displayName: displayName
              name: name
          serviceName: Platform
        type: type
        email: email
        providerType: Ad
      properties:
        accessType:
          $ref: '#/components/schemas/AdministratorAccessType'
        displayName:
          example: Jenny Rosen
          maxLength: 256
          minLength: 0
          nullable: true
          pattern: "^[^<>\\:\\/\\\\]*$"
          type: string
        email:
          format: email
          nullable: true
          type: string
        externalProviderId:
          maxLength: 8192
          minLength: 0
          type: string
        externalUserId:
          maxLength: 8192
          minLength: 0
          type: string
        firstName:
          example: Jenny
          maxLength: 256
          minLength: 0
          nullable: true
          pattern: "^[^<>\\:\\/\\\\]*$"
          type: string
        lastName:
          example: Rosen
          maxLength: 256
          minLength: 0
          nullable: true
          pattern: "^[^<>\\:\\/\\\\]*$"
          type: string
        policies:
          items:
            $ref: '#/components/schemas/AdministratorAccessPolicyModel'
          nullable: true
          type: array
        providerType:
          $ref: '#/components/schemas/AdministratorProviderType'
        type:
          minLength: 1
          type: string
      required:
      - accessType
      - providerType
      - type
      type: object
    EmbargoedPersonId:
      properties:
        embargoed:
          nullable: true
          type: boolean
        personId:
          maxLength: 100
          minLength: 0
          nullable: true
          type: string
      type: object
    PendingAdministratorInvite:
      properties:
        email:
          format: email
          minLength: 1
          type: string
        requestorEmail:
          format: email
          nullable: true
          type: string
        firstName:
          example: Jenny
          maxLength: 100
          minLength: 0
          nullable: true
          type: string
        lastName:
          example: Rosen
          maxLength: 100
          minLength: 0
          nullable: true
          type: string
        access:
          $ref: '#/components/schemas/AdministratorAccessModel'
      required:
      - email
      type: object
    PendingAdministratorInviteExternal:
      properties:
        email:
          format: email
          minLength: 1
          type: string
        requestorEmail:
          format: email
          nullable: true
          type: string
        firstName:
          maxLength: 100
          minLength: 0
          nullable: true
          type: string
        lastName:
          maxLength: 100
          minLength: 0
          nullable: true
          type: string
        access:
          $ref: '#/components/schemas/AdministratorAccessModel'
        displayName:
          maxLength: 100
          minLength: 0
          nullable: true
          type: string
        externalProviderType:
          $ref: '#/components/schemas/AdministratorExternalProviderType'
        externalProviderId:
          maxLength: 100
          minLength: 0
          type: string
        externalUserId:
          maxLength: 100
          minLength: 0
          type: string
        externalProviderProperties:
          additionalProperties: {}
          nullable: true
          type: object
        externalProviderAuthDomain:
          maxLength: 100
          minLength: 0
          nullable: true
          type: string
      required:
      - email
      - externalProviderId
      - externalProviderType
      - externalUserId
      type: object
    ProblemDetails:
      additionalProperties: {}
      example:
        instance: instance
        detail: detail
        type: type
        title: title
        status: 0
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
      type: object
    AdministratorResult_providerProperties:
      example:
        displayName: displayName
        tid: tid
      nullable: true
      properties:
        displayName:
          nullable: true
          type: string
        tid:
          nullable: true
          type: string
      type: object
